### ISSUE TITLE
Question on the client's file hashing and auditing

### ISSUE THREAD

**Issue by trevor-cockrell** [mlcommons/power-dev#175]
This is less of an issue and more of an observance/question. 

When running the `client` in the following example tree:
```
example
├── client.py
├── a_folder
│      ├── submission_files
│      ├── submission_files2
├── file_not_used_for_submission
└── all_other_submission_files
```
Every item from the root `example` downward gets hashed and logged into `<client_log_folder>/power/client.log` and in the same path, `client.json`.  This includes the file `file_not_used_for_submission`. 

The question is: if we then are to submit all files **except** our `file_not_used_for_submission`, will that affect the audit process and make our results invalid? Because now there exists a log that contains a file+its hash while said file does not exist in the official submissions repository. 

As our systems are performing multiple runs and also are used for development work, it is not viable for us to clean out the entire folder prior to every client run. 

Thanks!

**Comment by Lilit1122** [comment]
> The question is: if we then are to submit all files except our file_not_used_for_submission, will that affect the audit process and make our results invalid?
The unnecessary py files in the ptd_client_server folder can be a cause of the check.py tests fail. Other files will not have an effect on the audit process. If you have some py files in file_not_used_for_submission or in  all_other_submission_files you can rearrange your file structure the next way:
```
example
├── power
│      ├── client.py
│      ├── server.py
│      ├── lib
│      └── …
├── a_folder
│      ├── submission_files
│      ├── submission_files2
├── file_not_used_for_submission
└── all_other_submission_files```

**Comment by xzfc** [comment]
@trevor-cockrell
To be clear, you shouldn't put your code files inside the `ptd_client_server` directory, nor put `client.py` and `lib` inside your code directory (which is the same thing done in another way). Please leave the contents of this directory as-is.

These additional files may affect the runtime of `client.py`, that's how python works. E.g. create an empty file `example/argparse.py` along with `example/client.py` and see what will happen. That's why we don't allow it.
