### ISSUE TITLE
Every run fails with time difference failure

### ISSUE THREAD

**Issue by trevor-cockrell** [mlcommons/power-dev#205]
Currently every run that I attempt will fail with the error
```
[ ] Check time difference                                                 
        Loadgen test begin time is not within ranging mode time interval. 
```

I've tried relaunching the server, tried different NTP servers, and rebooting both director and server. 

The client/server is up to date with branch `r1.0` and the NTP check that is performed in the beginning places both systems within acceptable time difference.

**Comment by trevor-cockrell** [comment]
User error. I had thought both systems were in the same timezone but the daylight savings shift modified the zone/time of my director system.

**Comment by xzfc** [comment]
@trevor-cockrell 
Please send your log archive, so maybe we could handle timezones it or at least print more helpful error message.

**Comment by trevor-cockrell** [comment]
@xzfc after quick internal discussion we would be more comfortable releasing those logs once the results deadline has passed/results are locked in -- I have pulled the logs and stored them until and will release them to the team on Friday. Thanks! :)

**Comment by xzfc** [comment]
Ok. I'll reopen the issue and put it for the backlog for the next round 1.1.

**Comment by nvpohanh** [comment]
We also have this issue, and the root cause is: the client.py/server.py stores "time.timezone" as the "timezone" field in client.json/server.json. However, it does not store the "time.daylight" in the json field. In checker, when it is computing the Unix timestamp from the local time and timezone, the output timestamp is now off by 1 hr.

When I tried this on the machine:

```
>>> import time
>>> print(time.timezone)
28800
>>> print(time.daylight)
1
```

`time.timezone` still showed 28800 (which is UTC-8), but in reality it is only UTC-7 because of the daylight saving.
