### ISSUE TITLE
Change meter range from auto to max during ranging stage

### ISSUE THREAD

**Issue by ykurlaev** [mlcommons/power-dev#231]
@dmiskovic-NV suggested to change the meter range from the auto range to the max range to remove warnings and errors from PTD logs during the ranging stage.
See also discussions here #204 and here #219

**Comment by dmiskovic-NV** [comment]
@ykurlaev you brought up excellent point on the meeting. Different meters have different max range.
We can:
1) run PTD with few different ranges (100, 50, 30, 20, since those are more or less max ranges for meters in PTD) and use highest that doesn't PTD start to fail 
2) for each meter we want to use (or that exists in PTD), i can supply what is max range
3) we can use auto and hope it doesn't backstab us

problems/pitfalls:
approach 1) is that it introduces multiple runs of PTD and delays due to that
approach 2) is that you will need to have list of magic numbers in code (max range for each meter) whic is pain in the neck, but on the bright side, those max ranges are NOT subject to change
approach 3)  if there is spike in workload of few seconds, it might cause autorange to be confused and we might end up with lower range for perf run. Solution for that would be to see max current seen in sample before PTD returns "nan" and if that is highest current seen, increase it by 20% and use that as a range. Also, checker should be configured to clearly state that error from PTD has seen in ranging phase and print what might be the cause (i believe this is done already)

personally, I think approach 2) is least of gamble and might be best course of action

**Comment by ykurlaev** [comment]
@dmiskovic-NV Could you please post max range for PTD for each meter.

**Comment by dmiskovic-NV** [comment]
Yokogawa:
WT210: 20A
WT310/330/333: 20A
WT310EH: 40A
WT500: 40A
WT1800: 50A
WT5000: 30A

for whatever i don't get, use auto, but will get all in next few days

sources:
https://cdn.tmi.yokogawa.com/1/7115/files/IMWT5000-03EN.pdf
https://cdn.tmi.yokogawa.com/1/6197/files/IMWT310E-02EN.pdf
https://cdn.tmi.yokogawa.com/1/5959/files/IM760201-01E.pdf
https://cdn.tmi.yokogawa.com/1/5948/files/IMWT1801E-03EN.pdf
https://cdn.tmi.yokogawa.com/1/7115/files/IMWT5000-03EN.pdf

**Comment by ykurlaev** [comment]
Thanks @dmiskovic-NV Can you also provide numeric codes in PTD for these meters?

**Comment by dmiskovic-NV** [comment]
WT210: 8
WT310/WT310E/WT310EH/WT332E(single ch mode)/WT333E(single ch mode): 52
WT332E (multi ch mode)/WT333E (multi ch mode): 77
WT500 (single ch mode): 35
WT500 (multi ch mode): 48
WT1800: 47
WT5000: 66

**Comment by ykurlaev** [comment]
If WT310EH and WT310 has the same code will we not be able to use 40A?

**Comment by dmiskovic-NV** [comment]
good point. I will think of a better solution before we reconvene

**Comment by ykurlaev** [comment]
Is it ok to merge it with 20 for now?

**Comment by dmiskovic-NV** [comment]
It will be fine for now
