### ISSUE TITLE
Comparisons based on secondary or derived metrics must be explicit

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/power-dev#241]
An [proposed policy change](https://github.com/mlcommons/policies/pull/69/files) states that comparisons based on secondary or derived metrics must be explicit.

Performance is clearly a primary metric. Is power a primary or a secondary metric? In either case, a derived metric such as inferences per second per Watt would need to be presented alongside the primary metrics.

Are we good with that?

**Comment by TheKanter** [comment]
Anton: Could you please ask this question in the original PR discussion? https://github.com/mlcommons/policies/pull/69

**Comment by s-idgunji** [comment]
We cannot use any normalized metric because the metric is not constant:  Performance and Power do not scale linearly, so trying to do a ratio is misleading.  Performance and Power should continue to  be reported separately as has been done in r1.0

As regards primary or secondary metric , I do not understand the context of the question.  I would think that we'd need to go back to the WG where this was discussed or brought up rather than solve in Power WG.

**Comment by s-idgunji** [comment]
Moved my comments to the PR discussion : mlcommons/policies#69

We can close this issue
