### ISSUE TITLE
Unable to pass the compliance because of 200ms delta constraint

### ISSUE THREAD

**Issue by rakshithvasudev** [mlcommons/power-dev#262]
Since the [check.py](https://github.com/mlcommons/power-dev/blob/master/compliance/check.py) strictly checks to keep the time difference between SUT and director for <200ms, many of the tests fail this constraint. I'm attaching log files that didn't pass the 200ms constraint. 

[power_logs_failing_checks.tar.gz](https://github.com/mlcommons/power-dev/files/8766842/power_logs_failing_checks.tar.gz)

The ask would be to see if we can improve the checker to accept time delta to over 500ms.

**Comment by arjunsuresh** [comment]
[This PR](https://github.com/mlcommons/power-dev/pull/300) was supposed to fix this issue as many results were above 500ms. Unfortunately, we are still seeing some results above 500ms delta. For now, we are doing reruns.

**Comment by rakshithvasudev** [comment]
Thank you for the update @arjunsuresh, will run this as soon as I get access to meter and let you know if this still persists on our end too.

**Comment by arjunsuresh** [comment]
Thank you @rakshithvasudev . We observed this on a windows power server (some time delta between 500-700ms) - may be everything is fine on Linux :)

**Comment by rakshithvasudev** [comment]
Small sample size of one, seeing similar time delta, 620ms, using windows power server as well.

**Comment by arjunsuresh** [comment]
I think a 1s tolerance makes sense from the results seen so far. May be something for 4.0. We have seen about 10 results where the delta was between 500-750ms but nothing over that. As of now, rerunning is easier for us as it's very hard to manage some invalid results.

**Comment by arjunsuresh** [comment]
Completely agree. But I don't see a better option than increasing the delta to 1s or using a Linux server. Since we use GPIB linux is not an option and based on my experience during the last submission reruns are better than debating in the power WG :) 

Meanwhile, we are doing reruns only for the failed scenarios (about 15 minutes for a benchmark with a 5-minute long ranging mode run) and not for all scenarios. So, about 10 failures on 3-4 different systems can be less expensive than a 1 hr long meeting :) 3d-unet and gpt-j offline runs are where we needed good luck but fortunately we passed them.

**Comment by rakshithvasudev** [comment]
Thank you! Maybe worth trying setting up linux server and testing, next round possibly.
